[package]
name = "diskbenchi"
version = "0.1.0"
authors = ["yuezato <yuuya_uezato@dwango.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
structopt = "0.3"
